### ISSUE TITLE
注册不了

### ISSUE THREAD

**Issue by ZakiuC** [tkgs0/nonebot-plugin-dicky-pk#1]
### nonebot-plugin-dicky-pk 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

nonebot2最新的，python3.10.6,ubuntu22.04

### 如何复现

/注册牛子

### 期望行为

成功注册

### 实际行为

回复了：你还没有牛子！

**Comment by tkgs0** [comment]
请上传该条响应时的控制台输出截图  
以及启动Bot时的报红截图(如果有的话)

**Comment by ZakiuC** [comment]
添加了“”命令起始符后，使用/注册牛子命令正常了，原来的控制台没截到

**Comment by tkgs0** [comment]
> 添加了“”命令起始符后，使用/注册牛子命令正常了，原来的控制台没截到

我明白了, 是我使用了on_message响应器, 读取消息文本时发生的问题, 我尽快修
