### ISSUE TITLE
开启无效

### ISSUE THREAD

**Issue by ssszzza** [tkgs0/nonebot-plugin-dicky-pk#10]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-dicky-pk/issues) 中没有相同或相似的问题。

### dicky-pk

0.4.6

### go-cqhttp

我使用的是幻想乡

### nonebot

2.1.3

### Python

3.10.9

### 操作系统

win

### 问题描述

其他命令都可以正常运行，开启秘境的用不了
![Screenshot_2024-01-28-13-54-50-08_2665fb67b16260a8d818298cef8dc107](https://github.com/tkgs0/nonebot-plugin-dicky-pk/assets/117803055/54697c86-e1af-4e00-89e0-4f4b8a19917d)

### 复现步骤

1.运行//开启牛子秘境 2.没有效果

### 实际行为

没有回复

### 日志信息

![Screenshot_2024-01-28-13-54-50-08_2665fb67b16260a8d818298cef8dc107](https://github.com/tkgs0/nonebot-plugin-dicky-pk/assets/117803055/8a80ebc7-dbb4-4ed0-bd28-94fce3d94801)

**Comment by ssszzza** [comment]
![Uploading Screenshot_2024-01-29-08-35-38-43_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()

**Comment by ssszzza** [comment]
![Screenshot_2024-01-29-08-35-38-43_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/tkgs0/nonebot-plugin-dicky-pk/assets/117803055/055289bb-676a-4b05-8c7d-3c455a44a5e9)

**Comment by tkgs0** [comment]
未适配qq频道

**Comment by tkgs0** [comment]
我目前没有闲置的帐号来测试非gocq的前端, 无法复现你的问题, 抱歉.
可以尝试nonebot商店中其他类似功能的插件

**Comment by ssszzza** [comment]
> 我目前没有闲置的帐号来测试非gocq的前端， 无法复现你的问题， 抱歉. 可以尝试nonebot商店中其他类似功能的插件

没有吧

**Comment by NirvanafeLis** [comment]
![d9e23348b3fbd82c4ea115870ebe1a55](https://github.com/user-attachments/assets/1eca04f3-420e-47e0-9922-cbce57295ab9)

**Comment by NirvanafeLis** [comment]
我也出现了相同的问题 @tkgs0
