### ISSUE TITLE
看看bug

### ISSUE THREAD

**Issue by leimu293** [tkgs0/nonebot-plugin-dicky-pk#5]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-dicky-pk/issues) 中没有相同或相似的问题。

### dicky-pk

最新版本

### go-cqhttp

r4

### nonebot

0.6

### Python

3.10

### 操作系统

win

### 列出安装的 Python 包

![image](https://user-images.githubusercontent.com/108607907/218501581-c0a06783-5cec-44e5-94f3-c031fa955611.png)

### 问题描述

用了一天左右 出现这问题
![image](https://user-images.githubusercontent.com/108607907/218501721-a5bcf45f-f6fd-47b9-ad2c-9c86aa5d63af.png)

### 复现步骤

![image](https://user-images.githubusercontent.com/108607907/218502446-ed34cdfe-7cfe-425f-8e4a-fe4735f9b60d.png)

### 实际行为

![image](https://user-images.githubusercontent.com/108607907/218502524-d683f6e0-d457-403d-aa9a-e0edd43c2405.png)

### 日志信息

![image](https://user-images.githubusercontent.com/108607907/218502415-b9bac76a-0f89-4332-95de-aef7014c58a7.png)

### 额外补充

![image](https://user-images.githubusercontent.com/108607907/218501796-3e1e321b-d537-4a8c-91ca-087115b913fb.png)

**Comment by tkgs0** [comment]
如果您不知道如何有效、精准地提出一个问题，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
