### ISSUE TITLE
嗦自己有个bug，可以通过//嗦@自己 跳过//嗦我 的长度限制

### ISSUE THREAD

**Issue by liuzj288** [tkgs0/nonebot-plugin-dicky-pk#6]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-dicky-pk/issues) 中没有相同或相似的问题。

### dicky-pk

最新版本

### go-cqhttp

rc4

### nonebot

nb2

### Python

3.10

### 操作系统

win

### 问题描述

//嗦@自己  避开了 //嗦我 的长度限制

### 复现步骤

//嗦@自己  避开了 //嗦我 的长度限制

### 实际行为

//嗦@自己  避开了 //嗦我 的长度限制

### 日志信息

//嗦@自己  避开了 //嗦我 的长度限制

**Comment by tkgs0** [comment]
提issue前请组织一下语言 //
